import type {Metadata} from "next";
import {Inter} from "next/font/google";
import "../globals.css";
import {cn} from "@/lib/utils";
import {i18n, Locale} from "@/i18n-config";

const inter = Inter({subsets: ["latin"]});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export async function generateStaticParams() {
    return i18n.locales.map((locale) => ({ lang: locale }));
}

export default function RootLayout({
                                       children,
    params
                                   }: Readonly<{
    children: React.ReactNode;
    params: { lang: Locale}
}>) {
    return (
        <html lang={params.lang} suppressHydrationWarning>
        <body className={
            cn(
                "min-h-screen bg-background font-sans antialiased",
                inter.className
            )
        }>
        {
            children
        }
        </body>
        </html>
    );
}
